name: mgflutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  email_validator: ^1.0.0
  firebase_auth: ^0.16.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.7
  connectivity: ^0.4.4
  overlay_support: ^1.0.3
  flutter_launcher_icons: ^0.7.5
  country_icons: ^1.1.1
  http: ^0.12.1
  autocomplete_textfield: ^1.7.3
  image_picker: ^0.6.5+3
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/MG_Logo.png"